### ISSUE TITLE
Client Connected To Bot Message While There Is No One Online

### ISSUE THREAD

**Issue by xXxAaRkEtxXx** [PorkStudios/Pork2b2tBot#17] opened 2019-05-17 12:49 UTC

**Comment by xXxAaRkEtxXx** [comment] 2019-05-17 12:49
![image](https://user-images.githubusercontent.com/38191020/57929218-5dd57b00-78bb-11e9-89dc-e666614f9619.png)

**Comment by xXxAaRkEtxXx** [comment] 2019-05-17 12:50
oh i am connecting to the bot by the same account the bot is running... is that the matter? i have alts but they are my friend's alts

**Comment by DaMatrix** [comment] 2019-05-17 12:52
that could be the matter, is authentication turned on? if possible, send your config (with credentials removed) and debug log

**Comment by xXxAaRkEtxXx** [comment] 2019-05-17 12:58
```{
  "debug": {
    "printDataFields": false,
    "packet": {
      "received": false,
      "preSent": false,
      "postSent": false
    },
    "loglevel": "SIMPLE",
    "server": {
      "cache": {
        "unknownplayers": false,
        "printunknownplayers": false,
        "sendingmessages": true
      }
    }
  },
  "client": {
    "extra": {
      "autoreconnect": {
        "enabled": true
      },
      "antiafk": {
        "enabled": true,
        "runEvenIfClientsConnected": false,
        "actions": {
          "swingHand": true,
          "rotate": true
        }
      },
      "spammer": {
        "messages": [
          "#TeamBepis"
        ],
        "delaySeconds": 30,
        "enabled": false
      }
    },
    "server": {
      "address": "2b2t.org",
      "port": 25565
    }
  },
  "server": {
    "extra": {
      "whitelist": {
        "enable": false,
        "allowedusers": [
          "AaRkEt"
        ],
        "kickmsg": "get out of here you HECKING scrub"
      }
    },
    "enabled": true,
    "ping": {
      "favicon": true,
      "maxplayers": 2147483647,
      "motd": "ยงc%s"
    },
    "bind": {
      "address": "0.0.0.0",
      "port": 25565
    },
    "verifyusers": false,
    "compressionThreshold": 256
  },
  "log": {
    "ansi": true,
    "storeDebug": true
  },
  "gui": {
    "enabled": true,
    "messageCount": 512
  },
  "authentication": {
    "doAuthentication": true,
    "username": "succ@gmail.com",
    "password": "nope"
  }
}
```

**Comment by DaMatrix** [comment] 2019-05-17 13:00
hmm... authentication **is** turned off, so that shouldn't be an issue. could you try connecting with an alt account anyway, and tell me if it works? if it works then i know what the problem is

**Comment by xXxAaRkEtxXx** [comment] 2019-05-17 13:01
what do you mean is turned off? it is true

**Comment by DaMatrix** [comment] 2019-05-17 13:01
authentication for the server (as the bot is running a virtual server)

**Comment by xXxAaRkEtxXx** [comment] 2019-05-17 13:03
alt account doesn't work

**Comment by DaMatrix** [comment] 2019-05-17 13:04
same error? can you please send your debug log (upload it as a file or use pastebin)

**Comment by xXxAaRkEtxXx** [comment] 2019-05-17 13:04
yep 1 second

**Comment by xXxAaRkEtxXx** [comment] 2019-05-17 13:05
also after you close the gui the bot is still running and i cant delete/modify log files
![image](https://user-images.githubusercontent.com/38191020/57930047-a2621600-78bd-11e9-958a-8d4ccd245246.png)

**Comment by DaMatrix** [comment] 2019-05-17 13:07
you should be running it from the command line. when you have it opened in the command line you can press enter to close it, for now just use task manager to kill it

**Comment by xXxAaRkEtxXx** [comment] 2019-05-17 13:07
oh okay

**Comment by xXxAaRkEtxXx** [comment] 2019-05-17 13:09
[17.05.2019 16.07.27-debug.log](https://github.com/PorkStudios/Pork2b2tBot/files/3191601/17.05.2019.16.07.27-debug.log)
this is debug log

**Comment by DaMatrix** [comment] 2019-05-17 13:14
ok, i see what the issue is and will fix it when i get home. for now, change `server.verifyusers` to `true` and connect using an alt.

**Comment by xXxAaRkEtxXx** [comment] 2019-05-17 13:14
okay, is it in the jar?

**Comment by DaMatrix** [comment] 2019-05-17 13:15
no, in the config

![image](https://user-images.githubusercontent.com/11216106/57930573-9cb50200-78b6-11e9-96ce-a3d1eb1c0ca4.png)

**Comment by xXxAaRkEtxXx** [comment] 2019-05-17 13:15
oh okay, thanks

**Comment by xXxAaRkEtxXx** [comment] 2019-05-17 13:33
also also, please change this from
![image](https://user-images.githubusercontent.com/38191020/57931493-3f727e00-78c1-11e9-85dc-9dab7cbbdbc2.png)
to
![image](https://user-images.githubusercontent.com/38191020/57931527-51542100-78c1-11e9-9719-f946eab52d20.png)

i had to think why isnt it making a server
then i saw it, small change but worth it for new users

(also there are other instances where this happens)

**Comment by DaMatrix** [comment] 2019-05-17 13:34
the json data is sorted randomly (based on the string hashcode), i can't really control that afaik

**Comment by xXxAaRkEtxXx** [comment] 2019-05-17 13:34
oh okay

**Comment by xXxAaRkEtxXx** [comment] 2019-05-17 13:35
do you have any idea when you are going to fix the "client connected" bug?

**Comment by DaMatrix** [comment] 2019-05-17 13:38
i told you how to work around it temporarily, i'll have a chance to fix it in about 24 hours from now

**Comment by xXxAaRkEtxXx** [comment] 2019-05-17 13:41
okay

**Comment by xXxAaRkEtxXx** [comment] 2019-05-18 18:46
did you fix it?

**Comment by DaMatrix** [comment] 2019-05-20 16:27
ok i've tried like 6 different combinations and am unable to reproduce this. if somebody else is experiencing this issue i'll re-open this, but for now make sure you're running the latest version from jenkins and you should be fine. no idea how you managed to get this bug :/

**Closed by DaMatrix** 2019-05-20 16:27 UTC
Labels: bug

**Comment by xXxAaRkEtxXx** [comment] 2019-05-21 16:07
what's the jenkins url?

**Comment by xXxAaRkEtxXx** [comment] 2019-08-02 09:56
I FIXED IT

**Comment by xXxAaRkEtxXx** [comment] 2019-08-02 09:56
FINALLY, I DID IT.
